// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgozvlbjjteitekpnsqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nb3p2bGJqanRlaXRla3Buc3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTc0MTEsImV4cCI6MjA2MzY5MzQxMX0.BEek25ShT9j7Dn6dDOwhE0rByCt5ffoE-7YlB9rQ6vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);